#!/bin/bash
set -e

echo "[system] Building kernel"
find /usr/lib/modules -name vmlinuz | while read -r vmlinuz; do
  ln -s "$vmlinuz" /boot/vmlinuz-linux-zen
  chronic mkinitcpio -P
  rm /boot/vmlinuz-linux-zen
done

find /usr/lib/modules -maxdepth 1 -mindepth 1 -type d | while read -r dir; do
  mv /boot/initramfs-linux-zen.img "$dir/initramfs.img"
  break
done
