#!/bin/bash
set -e
echo "[system] Installing fakeroot debugedit pkg-config"
chronic pacman -Syu --needed --noconfirm fakeroot debugedit pkg-config
chronic useradd -m aur
chronic passwd -d aur
echo "aur ALL=(ALL:ALL) NOPASSWD: ALL" >/etc/sudoers.d/aur

for pkgref in "$@"; do
  echo "[system] Installing $pkgref"
  package=$(echo $pkgref | awk -F '=' '{print $1}')
  ref=$(echo $pkgref | awk -F '=' '{print $2}')
  if [[ "$ref" != "" ]]; then
    chronic sudo -u aur git clone \
      --depth=1 \
      --branch="$ref" \
      "https://aur.archlinux.org/${package}.git" \
      /tmp/src
  else
    chronic sudo -u aur git clone \
      --branch "$package" \
      --single-branch \
      https://github.com/archlinux/aur.git \
      /tmp/src
    # chronic sudo -u aur git clone \
    #   --depth=1 \
    #   "https://aur.archlinux.org/${package}.git" \
    #   /tmp/src
  fi
  cd /tmp/src
  sudo -u aur chronic makepkg \
    --noconfirm \
    --needed \
    --syncdeps \
    --install
  cd ..
  chronic rm -r src
done

chronic rm /etc/sudoers.d/aur
chronic userdel aur
chronic rm -r /home/aur

/usr/lib/system/remove_unused_packages
