#!/bin/bash
set -e
echo "[system] Build ID: ${BUILD_ID}"
if grep -Fq "BUILD_ID="; then
  sed -i "/BUILD_ID=/ s|.*|$BUILD_ID|" /usr/lib/os-release
else
  echo "BUILD_ID=${BUILD_ID}" >>/usr/lib/os-release
fi
