#!/bin/bash
set -e
buildid="${1}"

echo "[system] Build ID: ${buildid}"
if grep -Fq "BUILD_ID="; then
  sed -i "/BUILD_ID=/ s|.*|$buildid|" /etc/os-release
else
  echo "BUILD_ID=${buildid}" >>/etc/os-release
fi
