#!/bin/bash
set -e
echo "[system] Setting up live user"
chronic useradd -m live
chronic passwd -d live
echo "live ALL=(ALL:ALL) NOPASSWD: ALL" >/etc/sudoers.d/live
run-parts /usr/lib/system/setup_live_user.d
