name: Setup container for running containers
description: Setup container for running containers
runs:
  using: composite
  steps:
    - name: Setup container
      shell: bash
      run: |
        set -e
        cp /etc/resolv.conf /etc/hosts /etc/hostname /tmp/
        mount --make-rprivate /
        umount /etc/resolv.conf /etc/hosts /etc/hostname
        mv /tmp/resolv.conf /tmp/hosts /tmp/hostname /etc/
        mkdir -p /github/home/.docker /home/runner
        if ! [ -f /github/home/.docker/config.json ];then
          echo '{"auths":{}}' > /github/home/.docker/config.json
        fi
        if [ ! -f /etc/containers/seccomp.json ];then
          cp seccomp.json /etc/containers/seccomp.json
        fi
        echo "TMPDIR=${{ runner.temp }}" >> "$GITHUB_ENV"
        ln -s /__w /home/runner/work

    - name: Debug information
      shell: bash
      run: |
        df -h
        podman image ls
