name: Setup container for running containers
description: Setup container for running containers
runs:
  using: composite
  steps:
    - name: Setup container
      shell: bash
      run: |
        mkdir -p /github/home/.docker
        if ! [ -f /github/home/.docker/config.json ];then
          echo '{"auths":{}}' > /github/home/.docker/config.json
        fi
        if [ ! -f /etc/containers/seccomp.json ];then
          cp seccomp.json /etc/containers/seccomp.json
        fi
        echo "TMPDIR=${{ runner.temp }}" >> "$GITHUB_ENV"
