name: Upload container image
description: Upload a container image as a build artifact
inputs:
  image:
    description: Image to upload
    required: true
  name:
    description: Name of tag, and of artifact
    required: true
  if-no-files-found:
    description: Action to take if no files are found
    default: error
    required: false
outputs:
  digest:
    description: Digest of exported image
    value: ${{ fromJson(steps.export.outputs.outputs).digest }}
runs:
  using: "composite"
  steps:
    - name: Export image
      id: export
      uses: ./.github/actions/run-with-podman-service
      with:
        run: |
          set -e
          podman image ls
          skopeo copy \
            --preserve-digests \
            docker://$image \
            oci-archive:$tar:$name
          digest=$(skopeo inspect --format='{{.Digest}}' oci-archive:$tar:$name)
          zstd --rm -o $zstd $tar
          echo "Digest: $digest"
          echo "outputs<<EOF" >> $GITHUB_OUTPUT
          echo "{" >> $GITHUB_OUTPUT
          echo "\"path\":\"$zstd\"" >> $GITHUB_OUTPUT
          echo ",\"digest\":\"$digest\"" >> $GITHUB_OUTPUT
          echo "}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      env:
        image: ${{ inputs.image }}
        name: ${{ inputs.name }}
        tar: ${{ inputs.name }}.tar
        zstd: ${{ inputs.name }}.tar.zstd

    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ fromJson(steps.export.outputs.outputs).path }}
        if-no-files-found: ${{ inputs.if-no-files-found }}

    - name: Cleanup
      shell: bash
      run: rm ${{ fromJson(steps.export.outputs.outputs).path }}
