#!/bin/bash
set -e
echo "[system] Initializing keyring"
chronic pacman-key --init
echo "[system] populating keyring"
chronic pacman-key --populate
chronic run-parts /usr/lib/system/initialize_pacman.d
