#!/bin/bash
set -e

/usr/lib/system/initialize_pacman
packages=()
aur_packages=()
aur=false
for var in "$@"; do
  case "$var" in
  --aur)
    aur=true
    ;;
  *)
    if $aur; then
      aur_packages+=("$var")
    else
      packages+=("$var")
    fi
    ;;
  esac
done

if [ ${#packages[@]} -gt 0 ]; then
  /usr/lib/system/install_packages "${packages[@]}"
fi
if [ ${#aur_packages[@]} -gt 0 ]; then
  /usr/lib/system/install_aur_packages "${aur_packages[@]}"
fi
/usr/lib/system/remove_pacman_files
/usr/lib/system/commit_layer
