name: Run script with the podman service running
description: Run script with the podman service running
inputs:
  run:
    description: Script to run
    required: true
outputs:
  updates:
    description: If an update happened
    value: ${{ steps.run.outputs.updates }}
  outputs:
    description: Custom outputs
    value: ${{ steps.run.outputs.outputs }}
runs:
  using: composite
  steps:
    - name: Setup container
      id: run
      shell: bash
      run: |
        set -e
        mkdir -p /run/podman $TMPDIR
        podman system service --time 0 unix:///run/podman/podman.sock &
        ${{ inputs.run }}
        kill $(jobs -p) || true
