name: Import container
description: Import a container from a build artifact
inputs:
  artifact:
    description: Artifact to import
  image:
    description: Image to import
  prune:
    description: If podman system prune should happen first
    default: "true"
    required: false
runs:
  using: "composite"
  steps:
    - name: GC
      if: ${{ fromJson(inputs.prune) }}
      uses: ./.github/actions/run-with-podman-service
      with:
        run: podman system prune --force

    - name: Download image
      id: download
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact }}

    - name: Load image
      uses: ./.github/actions/run-with-podman-service
      with:
        run: |
          set -e
          cd "${{ steps.download.outputs.download-path }}"
          zstd \
            --rm -do \
            "${{ inputs.artifact }}.tar" \
            "${{ inputs.artifact }}.tar.zstd"
          skopeo copy \
            --preserve-digests \
            oci-archive:"${{ inputs.artifact }}.tar" \
            containers-storage:${{ inputs.image }}
          rm "${{ inputs.artifact }}.tar.zstd"
          podman image ls
