name: Restore the manifest cache
description: Restore the manifest cache
inputs:
  path:
    description: Path to cache
    default: ${{ runner.temp }}/manifest_cache
  key:
    description: Cache key
    default: manifest-cache-${{ github.ref_name }}
  artifact:
    description: Use artifact instead of cache
    default: "false"
    required: false
runs:
  using: composite
  steps:
    - uses: actions/cache/restore@v4
      if: inputs.artifact == 'false'
      with:
        path: ${{ inputs.path }}
        key: ${{ inputs.key }}

    - name: Download artifact
      id: download
      if: inputs.artifact == 'true'
      uses: actions/download-artifact@v5
      with:
        name: ${{ inputs.key }}
        path: ${{ inputs.path }}

    - name: Debug
      if: inputs.artifact == 'true'
      shell: bash
      run: ls -l ${{ steps.download.outputs.download-path }}
