#!/bin/bash
set -e
mkdir -p /etc/systemd/system/getty@tty1.service.d
cat >/etc/systemd/system/getty@tty1.service.d/autologin.conf <<EOF
[Service]
User=live
ExecStart=
ExecStart=-/sbin/agetty -o '-p -f -- \\u' --noclear --autologin live %I linux
EOF
