name: Cleanup
description: Free up space in the runner
inputs:
  root:
    description: Path to root directory
    default: /
    required: false
runs:
  using: "composite"
  steps:
    - name: Free up space
      shell: bash
      run: |
        chroot ${{ inputs.root }} /bin/bash -x <<'EOF'
          df -h
          echo
          echo Freeing up space
          rm -rf .git/
          docker system prune --force
          docker rmi $(docker image ls -aq) || true
          docker system prune --force
          export DEBIAN_FRONTEND="noninteractive"
          sudo apt-get autoremove -y
          sudo apt-get autoclean -y
          sudo rm -vrf \
            /usr/lib/jvm \
            /usr/share/dotnet \
            /usr/share/swift \
            /usr/local/.ghcup \
            /usr/local/julia* \
            /usr/local/lib/android \
            /usr/local/share/chromium \
            /opt/microsoft /opt/google \
            /opt/az \
            /usr/local/share/powershell \
          | wc -l
          echo
          df -h
        EOF
    - name: Podman GC
      uses: ./.github/actions/run-with-podman-service
      with:
        run: |
          df -h
          podman system prune --force
          podman rmi $(podman image ls -aq) || true
          podman system prune --force
          df -h
