name: Cleanup
description: Free up space in the runner
inputs:
  root:
    description: Path to root directory
    default: /
    required: false
runs:
  using: "composite"
  steps:
    - name: Free up space
      shell: bash
      run: |
        df -h
        echo
        echo Freeing up space
        rm -rf .git/
        docker system prune --force
        docker rmi $(docker image ls -aq) || true
        docker system prune --force
        export DEBIAN_FRONTEND="noninteractive"
        sudo apt-get -o Dir=${{ inputs.root }} autoremove -y
        sudo apt-get -o Dir=${{ inputs.root }} autoclean -y
        sudo rm -rf \
          ${{ inputs.root }}usr/lib/jvm \
          ${{ inputs.root }}usr/share/dotnet \
          ${{ inputs.root }}usr/share/swift \
          ${{ inputs.root }}usr/local/.ghcup \
          ${{ inputs.root }}usr/local/julia* \
          ${{ inputs.root }}usr/local/lib/android \
          ${{ inputs.root }}usr/local/share/chromium \
          ${{ inputs.root }}opt/microsoft /opt/google \
          ${{ inputs.root }}opt/az \
          ${{ inputs.root }}usr/local/share/powershell
        echo
        df -h
