name: Update the manifest cache
description: Update the manifest cache
inputs:
  path:
    description: Path to cache
    default: ${{ runner.temp }}/manifest_cache
  key:
    description: Cache key
    default: manifest-cache-${{ github.ref_name }}
  token:
    description: Github token to use to delete the cache
    default: ${{ github.token }}
    required: false
  artifact:
    description: Use artifact instead of cache
    default: "false"
    required: false
runs:
  using: composite
  steps:
    - name: Remove old cache
      if: inputs.artifact == 'false'
      shell: bash
      continue-on-error: true
      run: |
        git config --global --add safe.directory "$(realpath .)"
        gh cache delete \
          "${{ inputs.key }}" \
          --repo "${{ github.repository }}"
      env:
        GH_TOKEN: ${{ inputs.token }}

    - uses: actions/cache/save@v4
      if: inputs.artifact == 'false'
      with:
        path: ${{ inputs.path }}
        key: ${{ inputs.key }}

    - uses: actions/upload-artifact@v5
      if: inputs.artifact == 'true'
      with:
        path: ${{ inputs.path }}
        name: ${{ inputs.key }}
        overwrite: true
        if-no-files-found: error
